name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check code formatting (Spotless)
        run: ./gradlew spotlessCheck

      - name: Build project
        run: ./gradlew build -x test

      - name: Run tests
        run: ./gradlew test
